"""initial migeration

Revision ID: 3a14d83698d8
Revises: 
Create Date: 2023-08-15 19:02:20.929445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a14d83698d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_products')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('brand_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('state')
        batch_op.drop_column('address')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('brand_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.create_table('_alembic_tmp_products',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('discount', sa.INTEGER(), nullable=True),
    sa.Column('stock', sa.INTEGER(), nullable=False),
    sa.Column('colors', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('date_created', sa.DATETIME(), nullable=False),
    sa.Column('image_1', sa.VARCHAR(length=180), nullable=False),
    sa.Column('image_2', sa.VARCHAR(length=180), nullable=False),
    sa.Column('image_3', sa.VARCHAR(length=180), nullable=False),
    sa.Column('image_4', sa.VARCHAR(length=180), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=True),
    sa.Column('brand_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
